name: simple_auth
description: A new flutter package project.
version: 0.0.1
author: James Clancey
homepage:

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  http: "^0.11.0"
  meta: ^1.1.2

dev_dependencies:
  test: ^0.12.0
