name: simple_auth_generator
description: simple_auth is an http client generator using source_gen and inspired from retrofit and chopper
version: 1.0.4
homepage: https://github.com/clancey/simple_auth
author: James Clancey <james.clancey@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  simple_auth: ^1.0.4
  analyzer:
  build:
  build_config:
  logging:
  meta:
  path: 
  source_gen:
  code_builder:
  dart_style:
dev_dependencies:
  test:

dependency_overrides:
  simple_auth:
    path: ../simple_auth